spring:
  application:
    name: BOOK-NOW
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          provider_class: net.sf.ehcache.hibernate.EhCacheProvider
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
            
logging:
  level:
    net:
      sf:
        ehcache: debug


management:
  endpoint:
    health:
      enabled: true
     
    
server:
  port: 8080
  
  
booknow:
  dateformat: "yyyy-MM-dd"
  threadPoolSize: 20
