spring:
  flyway:
    locations: classpath:/db/migration/h2
  datasource:
    url: jdbc:h2:mem:booknow;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    platform: h2
    username: test
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
    